modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "exoconfig"
version = "${version}"
displayName = "ExoConfig"
authors = "TATHAN"
description = '''
A Simple config lib based on auto screen config
'''
#logoFile = ""

[[dependencies.exoconfig]]
modId = "neoforge"
type = "required"
versionRange = "[21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.exoconfig]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"
